language: node_js

node_js:
  - "stable"

sudo: true

env:
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE tip_test;" -U postgres
  - node_modules/.bin/sequelize db:migrate

script:
  - npm test
  