language: node_js

dist: precise

node_js:
  - "10"

sudo: true

cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g sequelize sequelize-cli pg mysql2

env:
  - CXX=g++-4.8
  - DB_NAME=tip_test
  - DB_HOST=localhost
  - NODE_API_DB_NAME_TEST=tip_test
  - DB_USERNAME=travis

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE tip_test;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON tip_test.* TO 'travis'@'%';";

test:
  adapter: mysql2
  database: tip_test
  username: travis
  encoding: utf8
  