language: node_js

node_js:
  - "10"

sudo: true

cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g sequelize sequelize-cli pg

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE tip_test;" -U postgres
  - sequelize db:migrate

script:
  - npm test
  