language: node_js

dist: precise

node_js:
  - "10"

sudo: true

cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g sequelize sequelize-cli pg mysql2

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE tip_test;'

test:
  adapter: mysql2
  database: tip_test
  username: travis
  encoding: utf8
  