language: node_js
node_js:
  - "10"
env:
  global:
    # Necessary to build Node.js 0.6 on Travis CI images
    - "CC=gcc-4.6 CXX=g++-4.6"

dist: trusty
addons:
  apt:
    packages:
      - g++-4.6
sudo: required

cache:
  directories:
    - node_modules

before_install:
  # Setup Node.js version-specific dependencies
  - "mysql -e 'CREATE DATABASE tip_test;'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON tip_test.* TO 'root'@'%';";

  # Setup environment
  - "export MYSQL_DATABASE=tip_test"
  - "export MYSQL_HOST=localhost"
  - "export MYSQL_PORT=3306"
  - "export MYSQL_USER=root"
  - "export DB_HOST=localhost"
  - "export DB_USERNAME=root"
  - "export DB_PORT=3306"
  - "export DB_HOST=root"
  - "export DB_NAME=tip_test"
  - "export NODE_API_DB_NAME_TEST=tip_test"

install:
  - "npm install"
  - "npm install -g sequelize sequelize-cli pg mysql2"

script:
  # Run test script
  - "npm test"