language: node_js

node_js:
  - "10"

sudo: true

cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g sequelize sequelize-cli pg mysql2

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mysql

before_script:
  - NODE_ENV=testing sequelize db:create
  - NODE_ENV=testing sequelize db:migrate

script:
  - npm test
  